[2024-11-25T13:34:39.036+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:39.091+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T13:34:39.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T13:34:39.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:39.145+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 00:00:00+00:00
[2024-11-25T13:34:39.166+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:39.169+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2024-11-25T13:34:39.173+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpl0xxk01d']
[2024-11-25T13:34:39.180+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask load
[2024-11-25T13:34:39.221+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:39.298+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:39.480+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T00:00:00+00:00'
[2024-11-25T13:34:39.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:40.212+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:40.214+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:40.261+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T00:00:00+00:00, execution_date=20241125T000000, start_date=20241125T133439, end_date=20241125T133440
[2024-11-25T13:34:40.296+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 33 for task load (Missing required database environment variables.; 289)
[2024-11-25T13:34:40.365+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:40.388+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T13:48:23.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:48:23.638+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T13:48:23.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T13:48:23.651+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:48:23.681+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 00:00:00+00:00
[2024-11-25T13:48:23.692+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:48:23.691+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp5tzph71h']
[2024-11-25T13:48:23.693+0000] {standard_task_runner.py:63} INFO - Started process 283 to run task
[2024-11-25T13:48:23.693+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask load
[2024-11-25T13:48:23.733+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:48:23.768+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T13:48:23.936+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T00:00:00+00:00'
[2024-11-25T13:48:23.938+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:48:24.340+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T13:48:24.383+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T13:48:24.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:48:24.410+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T00:00:00+00:00, execution_date=20241125T000000, start_date=20241125T134823, end_date=20241125T134824
[2024-11-25T13:48:24.552+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T13:48:24.597+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:48:24.604+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:22.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:22.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T16:19:22.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T16:19:22.473+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:22.622+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 00:00:00+00:00
[2024-11-25T16:19:22.653+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=294) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:22.657+0000] {standard_task_runner.py:63} INFO - Started process 326 to run task
[2024-11-25T16:19:22.662+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpi36x__6n']
[2024-11-25T16:19:22.671+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load
[2024-11-25T16:19:22.730+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:22.823+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:23.010+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T00:00:00+00:00'
[2024-11-25T16:19:23.014+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:23.519+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:23.521+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:23.522+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:23.535+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T00:00:00+00:00, execution_date=20241125T000000, start_date=20241125T161922, end_date=20241125T161923
[2024-11-25T16:19:23.646+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:23.667+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:23.672+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:10.914+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:10.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T16:30:10.991+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [queued]>
[2024-11-25T16:30:10.992+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:11.028+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 00:00:00+00:00
[2024-11-25T16:30:11.047+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:11.049+0000] {standard_task_runner.py:63} INFO - Started process 308 to run task
[2024-11-25T16:30:11.047+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp865f2p4f']
[2024-11-25T16:30:11.051+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask load
[2024-11-25T16:30:11.082+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:11.157+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T00:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:11.395+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T00:00:00+00:00'
[2024-11-25T16:30:11.406+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:12.742+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:12.745+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:12.746+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:12.759+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T00:00:00+00:00, execution_date=20241125T000000, start_date=20241125T163010, end_date=20241125T163012
[2024-11-25T16:30:12.850+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:12.866+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
