[2024-11-25T13:34:39.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:39.092+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T13:34:39.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T13:34:39.108+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:39.145+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 05:00:00+00:00
[2024-11-25T13:34:39.164+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=266) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:39.169+0000] {standard_task_runner.py:63} INFO - Started process 288 to run task
[2024-11-25T13:34:39.169+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T05:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpefum3e59']
[2024-11-25T13:34:39.176+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask load
[2024-11-25T13:34:39.218+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:39.284+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:39.451+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T05:00:00+00:00'
[2024-11-25T13:34:39.454+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:40.173+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:40.175+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:40.206+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T05:00:00+00:00, execution_date=20241125T050000, start_date=20241125T133439, end_date=20241125T133440
[2024-11-25T13:34:40.231+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task load (Missing required database environment variables.; 288)
[2024-11-25T13:34:40.280+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:40.327+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:34:40.343+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T13:48:23.608+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:48:23.653+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T13:48:23.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T13:48:23.665+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:48:23.705+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 05:00:00+00:00
[2024-11-25T13:48:23.719+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:48:23.721+0000] {standard_task_runner.py:63} INFO - Started process 288 to run task
[2024-11-25T13:48:23.720+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T05:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpthbqa7er']
[2024-11-25T13:48:23.724+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask load
[2024-11-25T13:48:23.793+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:48:23.843+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T13:48:24.051+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T05:00:00+00:00'
[2024-11-25T13:48:24.055+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:48:24.725+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T13:48:24.726+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T13:48:24.727+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:48:24.741+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T05:00:00+00:00, execution_date=20241125T050000, start_date=20241125T134823, end_date=20241125T134824
[2024-11-25T13:48:24.828+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T13:48:24.842+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:48:24.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:23.377+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:23.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T16:19:23.432+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T16:19:23.433+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:23.461+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 05:00:00+00:00
[2024-11-25T16:19:23.480+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=310) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:23.482+0000] {standard_task_runner.py:63} INFO - Started process 332 to run task
[2024-11-25T16:19:23.480+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T05:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp_7shrvju']
[2024-11-25T16:19:23.484+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask load
[2024-11-25T16:19:23.511+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:23.555+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:23.670+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T05:00:00+00:00'
[2024-11-25T16:19:23.673+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:24.003+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:24.005+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:24.006+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:24.017+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T05:00:00+00:00, execution_date=20241125T050000, start_date=20241125T161923, end_date=20241125T161924
[2024-11-25T16:19:24.059+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:24.072+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:10.832+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:10.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T16:30:10.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [queued]>
[2024-11-25T16:30:10.916+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:10.947+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 05:00:00+00:00
[2024-11-25T16:30:10.966+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=265) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:10.968+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-11-25T16:30:10.967+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T05:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp_aotc9b7']
[2024-11-25T16:30:10.973+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask load
[2024-11-25T16:30:10.999+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:11.079+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T05:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:11.226+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T05:00:00+00:00'
[2024-11-25T16:30:11.229+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:12.719+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:12.720+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:12.721+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:12.731+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T05:00:00+00:00, execution_date=20241125T050000, start_date=20241125T163010, end_date=20241125T163012
[2024-11-25T16:30:12.841+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:12.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
