[2024-11-25T13:34:39.032+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:39.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T13:34:39.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T13:34:39.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:39.145+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 02:00:00+00:00
[2024-11-25T13:34:39.164+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=265) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:39.169+0000] {standard_task_runner.py:63} INFO - Started process 287 to run task
[2024-11-25T13:34:39.178+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T02:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpke0nlxbx']
[2024-11-25T13:34:39.182+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask load
[2024-11-25T13:34:39.221+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:39.292+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:39.469+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T02:00:00+00:00'
[2024-11-25T13:34:39.473+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:40.195+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:40.196+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:40.218+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T02:00:00+00:00, execution_date=20241125T020000, start_date=20241125T133439, end_date=20241125T133440
[2024-11-25T13:34:40.249+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task load (Missing required database environment variables.; 287)
[2024-11-25T13:34:40.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:40.359+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T13:48:23.561+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:48:23.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T13:48:23.618+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T13:48:23.619+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:48:23.646+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 02:00:00+00:00
[2024-11-25T13:48:23.660+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=262) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:48:23.661+0000] {standard_task_runner.py:63} INFO - Started process 282 to run task
[2024-11-25T13:48:23.660+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T02:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp9x7piak2']
[2024-11-25T13:48:23.663+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask load
[2024-11-25T13:48:23.705+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:48:23.755+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T13:48:23.937+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T02:00:00+00:00'
[2024-11-25T13:48:23.943+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:48:24.340+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T13:48:24.343+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T13:48:24.344+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:48:24.371+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T02:00:00+00:00, execution_date=20241125T020000, start_date=20241125T134823, end_date=20241125T134824
[2024-11-25T13:48:24.522+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T13:48:24.562+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:48:24.576+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:22.367+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:22.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T16:19:22.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T16:19:22.455+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:22.618+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 02:00:00+00:00
[2024-11-25T16:19:22.639+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=293) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:22.641+0000] {standard_task_runner.py:63} INFO - Started process 321 to run task
[2024-11-25T16:19:22.650+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T02:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpyzmwtf7q']
[2024-11-25T16:19:22.657+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask load
[2024-11-25T16:19:22.715+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:22.792+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:22.970+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T02:00:00+00:00'
[2024-11-25T16:19:22.977+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:23.464+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:23.465+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:23.466+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:23.485+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T02:00:00+00:00, execution_date=20241125T020000, start_date=20241125T161922, end_date=20241125T161923
[2024-11-25T16:19:23.548+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:23.565+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:23.582+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:10.864+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:10.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T16:30:10.935+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [queued]>
[2024-11-25T16:30:10.937+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:10.977+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 02:00:00+00:00
[2024-11-25T16:30:10.993+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:10.996+0000] {standard_task_runner.py:63} INFO - Started process 306 to run task
[2024-11-25T16:30:10.996+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T02:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpcn0vy6ez']
[2024-11-25T16:30:11.000+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask load
[2024-11-25T16:30:11.047+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:11.114+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T02:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:11.265+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T02:00:00+00:00'
[2024-11-25T16:30:11.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:12.742+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:12.745+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:12.747+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:12.759+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T02:00:00+00:00, execution_date=20241125T020000, start_date=20241125T163010, end_date=20241125T163012
[2024-11-25T16:30:12.881+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:12.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
