[2024-11-25T13:34:41.086+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:41.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T13:34:41.133+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T13:34:41.133+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:41.151+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 09:00:00+00:00
[2024-11-25T13:34:41.161+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T09:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpye45gxbs']
[2024-11-25T13:34:41.163+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=295) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:41.165+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask load
[2024-11-25T13:34:41.166+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-11-25T13:34:41.184+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:41.236+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:41.355+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T09:00:00+00:00'
[2024-11-25T13:34:41.356+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:41.619+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:41.620+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:41.642+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T09:00:00+00:00, execution_date=20241125T090000, start_date=20241125T133441, end_date=20241125T133441
[2024-11-25T13:34:41.661+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task load (Missing required database environment variables.; 303)
[2024-11-25T13:34:41.702+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:41.725+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:34:41.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T13:48:23.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:48:23.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T13:48:23.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T13:48:23.658+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:48:23.705+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 09:00:00+00:00
[2024-11-25T13:48:23.719+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=258) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:48:23.722+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2024-11-25T13:48:23.720+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T09:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp8j2hy1kk']
[2024-11-25T13:48:23.723+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask load
[2024-11-25T13:48:23.794+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:48:23.843+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T13:48:24.053+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T09:00:00+00:00'
[2024-11-25T13:48:24.055+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:48:24.720+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T13:48:24.721+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T13:48:24.722+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:48:24.736+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T09:00:00+00:00, execution_date=20241125T090000, start_date=20241125T134823, end_date=20241125T134824
[2024-11-25T13:48:24.824+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T13:48:24.839+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:48:24.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:23.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:23.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T16:19:23.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T16:19:23.720+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:23.746+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 09:00:00+00:00
[2024-11-25T16:19:23.760+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=320) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:23.761+0000] {standard_task_runner.py:63} INFO - Started process 336 to run task
[2024-11-25T16:19:23.761+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T09:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpeintxypc']
[2024-11-25T16:19:23.764+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask load
[2024-11-25T16:19:23.785+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:23.842+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:23.940+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T09:00:00+00:00'
[2024-11-25T16:19:23.942+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:24.222+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:24.223+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:24.224+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:24.241+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T09:00:00+00:00, execution_date=20241125T090000, start_date=20241125T161923, end_date=20241125T161924
[2024-11-25T16:19:24.297+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:24.314+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:24.317+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:11.430+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:11.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T16:30:11.586+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [queued]>
[2024-11-25T16:30:11.594+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:11.714+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 09:00:00+00:00
[2024-11-25T16:30:11.772+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T09:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp2eqx2f7l']
[2024-11-25T16:30:11.770+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=293) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:11.794+0000] {standard_task_runner.py:63} INFO - Started process 311 to run task
[2024-11-25T16:30:11.790+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask load
[2024-11-25T16:30:12.259+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:12.289+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T09:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:12.828+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T09:00:00+00:00'
[2024-11-25T16:30:12.836+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:13.162+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:13.162+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:13.163+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:13.170+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T09:00:00+00:00, execution_date=20241125T090000, start_date=20241125T163011, end_date=20241125T163013
[2024-11-25T16:30:13.217+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:13.230+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:30:13.234+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
