[2024-11-25T13:34:39.040+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:39.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T13:34:39.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T13:34:39.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:39.160+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 01:00:00+00:00
[2024-11-25T13:34:39.186+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:39.188+0000] {standard_task_runner.py:63} INFO - Started process 290 to run task
[2024-11-25T13:34:39.186+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T01:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp33enr7ff']
[2024-11-25T13:34:39.192+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask load
[2024-11-25T13:34:39.228+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:39.294+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:39.469+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T01:00:00+00:00'
[2024-11-25T13:34:39.475+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:40.193+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:40.194+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:40.217+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T01:00:00+00:00, execution_date=20241125T010000, start_date=20241125T133439, end_date=20241125T133440
[2024-11-25T13:34:40.255+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task load (Missing required database environment variables.; 290)
[2024-11-25T13:34:40.306+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:40.337+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T13:48:23.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:48:23.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T13:48:23.651+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T13:48:23.652+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:48:23.700+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 01:00:00+00:00
[2024-11-25T13:48:23.714+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=257) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:48:23.717+0000] {standard_task_runner.py:63} INFO - Started process 287 to run task
[2024-11-25T13:48:23.724+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T01:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp16d3vclp']
[2024-11-25T13:48:23.726+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask load
[2024-11-25T13:48:23.793+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:48:23.843+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T13:48:24.051+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T01:00:00+00:00'
[2024-11-25T13:48:24.055+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:48:24.724+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T13:48:24.725+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T13:48:24.726+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:48:24.739+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T01:00:00+00:00, execution_date=20241125T010000, start_date=20241125T134823, end_date=20241125T134824
[2024-11-25T13:48:24.820+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T13:48:24.837+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:48:24.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:22.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:22.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T16:19:22.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T16:19:22.432+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:22.622+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 01:00:00+00:00
[2024-11-25T16:19:22.641+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:22.644+0000] {standard_task_runner.py:63} INFO - Started process 323 to run task
[2024-11-25T16:19:22.650+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T01:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpbrf64vft']
[2024-11-25T16:19:22.658+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask load
[2024-11-25T16:19:22.710+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:22.796+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:22.970+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T01:00:00+00:00'
[2024-11-25T16:19:22.977+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:23.464+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:23.465+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:23.466+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:23.484+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T01:00:00+00:00, execution_date=20241125T010000, start_date=20241125T161922, end_date=20241125T161923
[2024-11-25T16:19:23.565+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:23.580+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:23.585+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:10.830+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:10.880+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T16:30:10.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [queued]>
[2024-11-25T16:30:10.898+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:10.944+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 01:00:00+00:00
[2024-11-25T16:30:10.967+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T01:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpzg8k0umf']
[2024-11-25T16:30:10.969+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=266) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:10.972+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load
[2024-11-25T16:30:10.973+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2024-11-25T16:30:10.999+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:11.083+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T01:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:11.229+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T01:00:00+00:00'
[2024-11-25T16:30:11.232+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:12.742+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:12.745+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:12.746+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:12.757+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T01:00:00+00:00, execution_date=20241125T010000, start_date=20241125T163010, end_date=20241125T163012
[2024-11-25T16:30:12.835+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:12.850+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
