[2024-11-25T13:34:41.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:41.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T13:34:41.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T13:34:41.166+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:41.195+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 11:00:00+00:00
[2024-11-25T13:34:41.208+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=297) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:41.210+0000] {standard_task_runner.py:63} INFO - Started process 305 to run task
[2024-11-25T13:34:41.208+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T11:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp45_1m0jt']
[2024-11-25T13:34:41.212+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask load
[2024-11-25T13:34:41.235+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:41.293+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:41.410+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T11:00:00+00:00'
[2024-11-25T13:34:41.413+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:41.643+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:41.644+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:41.668+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T11:00:00+00:00, execution_date=20241125T110000, start_date=20241125T133441, end_date=20241125T133441
[2024-11-25T13:34:41.684+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task load (Missing required database environment variables.; 305)
[2024-11-25T13:34:41.709+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:41.729+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:34:41.734+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T13:48:26.750+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:48:26.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T13:48:26.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T13:48:26.782+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:48:26.793+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 11:00:00+00:00
[2024-11-25T13:48:26.802+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=295) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:48:26.803+0000] {standard_task_runner.py:63} INFO - Started process 300 to run task
[2024-11-25T13:48:26.802+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T11:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpai7sbjvq']
[2024-11-25T13:48:26.804+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask load
[2024-11-25T13:48:26.819+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:48:26.849+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T13:48:26.927+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T11:00:00+00:00'
[2024-11-25T13:48:26.929+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:48:27.088+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T13:48:27.089+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T13:48:27.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:48:27.097+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T11:00:00+00:00, execution_date=20241125T110000, start_date=20241125T134826, end_date=20241125T134827
[2024-11-25T13:48:27.137+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T13:48:27.151+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:48:27.171+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:24.624+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:24.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T16:19:24.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T16:19:24.659+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:24.678+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 11:00:00+00:00
[2024-11-25T16:19:24.688+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=337) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:24.690+0000] {standard_task_runner.py:63} INFO - Started process 350 to run task
[2024-11-25T16:19:24.694+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T11:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpu3fvpynm']
[2024-11-25T16:19:24.696+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask load
[2024-11-25T16:19:24.730+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:24.764+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:24.858+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T11:00:00+00:00'
[2024-11-25T16:19:24.860+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:25.166+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:25.167+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:25.167+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:25.178+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T11:00:00+00:00, execution_date=20241125T110000, start_date=20241125T161924, end_date=20241125T161925
[2024-11-25T16:19:25.226+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:25.245+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:25.251+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:13.965+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:14.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T16:30:14.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [queued]>
[2024-11-25T16:30:14.035+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:14.048+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 11:00:00+00:00
[2024-11-25T16:30:14.058+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=316) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:14.058+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T11:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpbrv2cah2']
[2024-11-25T16:30:14.060+0000] {standard_task_runner.py:63} INFO - Started process 325 to run task
[2024-11-25T16:30:14.060+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask load
[2024-11-25T16:30:14.081+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:14.112+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T11:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:14.189+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T11:00:00+00:00'
[2024-11-25T16:30:14.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:14.458+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:14.459+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:14.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:14.467+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T11:00:00+00:00, execution_date=20241125T110000, start_date=20241125T163014, end_date=20241125T163014
[2024-11-25T16:30:14.515+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:14.529+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:30:14.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
