[2024-11-25T13:34:42.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:34:42.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T13:34:42.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T13:34:42.661+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:34:42.692+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 12:00:00+00:00
[2024-11-25T13:34:42.712+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:34:42.712+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T12:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpdinwtljg']
[2024-11-25T13:34:42.715+0000] {standard_task_runner.py:63} INFO - Started process 309 to run task
[2024-11-25T13:34:42.717+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask load
[2024-11-25T13:34:42.751+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:34:42.837+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [running]> on host 8a6a192a668b
[2024-11-25T13:34:42.992+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T12:00:00+00:00'
[2024-11-25T13:34:42.994+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:34:43.219+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:34:43.220+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-25T13:34:43.253+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T12:00:00+00:00, execution_date=20241125T120000, start_date=20241125T133442, end_date=20241125T133443
[2024-11-25T13:34:43.268+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task load (Missing required database environment variables.; 309)
[2024-11-25T13:34:43.297+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T13:34:43.320+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:34:43.325+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T13:48:26.746+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T13:48:26.770+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T13:48:26.778+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T13:48:26.778+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T13:48:26.791+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 12:00:00+00:00
[2024-11-25T13:48:26.799+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T13:48:26.800+0000] {standard_task_runner.py:63} INFO - Started process 299 to run task
[2024-11-25T13:48:26.799+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T12:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp6d2drg5k']
[2024-11-25T13:48:26.801+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask load
[2024-11-25T13:48:26.816+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T13:48:26.849+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T13:48:26.930+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T12:00:00+00:00'
[2024-11-25T13:48:26.931+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T13:48:27.088+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T13:48:27.089+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T13:48:27.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T13:48:27.097+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T12:00:00+00:00, execution_date=20241125T120000, start_date=20241125T134826, end_date=20241125T134827
[2024-11-25T13:48:27.135+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T13:48:27.149+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T13:48:27.169+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:24.610+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:24.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T16:19:24.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T16:19:24.645+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:24.675+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 12:00:00+00:00
[2024-11-25T16:19:24.685+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=338) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:24.687+0000] {standard_task_runner.py:63} INFO - Started process 349 to run task
[2024-11-25T16:19:24.685+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T12:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpv25nx9eo']
[2024-11-25T16:19:24.689+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask load
[2024-11-25T16:19:24.727+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:24.762+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:24.858+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T12:00:00+00:00'
[2024-11-25T16:19:24.861+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:25.115+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:25.116+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:25.117+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:25.126+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T12:00:00+00:00, execution_date=20241125T120000, start_date=20241125T161924, end_date=20241125T161925
[2024-11-25T16:19:25.185+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:25.206+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:25.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:13.964+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:14.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T16:30:14.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [queued]>
[2024-11-25T16:30:14.027+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:14.043+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 12:00:00+00:00
[2024-11-25T16:30:14.052+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=314) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:14.054+0000] {standard_task_runner.py:63} INFO - Started process 323 to run task
[2024-11-25T16:30:14.052+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T12:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp4j9r2m_c']
[2024-11-25T16:30:14.055+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask load
[2024-11-25T16:30:14.081+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:14.112+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T12:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:14.191+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T12:00:00+00:00'
[2024-11-25T16:30:14.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:14.458+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:14.459+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:14.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:14.467+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T12:00:00+00:00, execution_date=20241125T120000, start_date=20241125T163014, end_date=20241125T163014
[2024-11-25T16:30:14.509+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:14.523+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:30:14.527+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
