[2024-11-22T17:15:20.561+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T17:15:20.582+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load manual__2024-11-22T17:14:15.605514+00:00 [queued]>
[2024-11-22T17:15:20.588+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load manual__2024-11-22T17:14:15.605514+00:00 [queued]>
[2024-11-22T17:15:20.589+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-22T17:15:20.602+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-22 17:14:15.605514+00:00
[2024-11-22T17:15:20.608+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=396) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T17:15:20.608+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'manual__2024-11-22T17:14:15.605514+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmp83k3pg_g']
[2024-11-22T17:15:20.609+0000] {standard_task_runner.py:63} INFO - Started process 398 to run task
[2024-11-22T17:15:20.609+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask load
[2024-11-22T17:15:20.624+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-22T17:15:20.651+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load manual__2024-11-22T17:14:15.605514+00:00 [running]> on host a1631a591e38
[2024-11-22T17:15:20.709+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T17:14:15.605514+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T17:14:15.605514+00:00'
[2024-11-22T17:15:20.710+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T17:15:20.848+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T17:15:20.849+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/load.py", line 25, in load_data_to_postgres
    raise ValueError("Missing required database environment variables.")
ValueError: Missing required database environment variables.
[2024-11-22T17:15:20.863+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather-forecast-dag, task_id=load, run_id=manual__2024-11-22T17:14:15.605514+00:00, execution_date=20241122T171415, start_date=20241122T171520, end_date=20241122T171520
[2024-11-22T17:15:20.873+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 113 for task load (Missing required database environment variables.; 398)
[2024-11-22T17:15:20.904+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T17:15:20.917+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T17:15:20.921+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
