[2024-11-25T14:00:04.903+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T14:00:04.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [queued]>
[2024-11-25T14:00:04.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [queued]>
[2024-11-25T14:00:04.931+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T14:00:04.942+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 13:00:00+00:00
[2024-11-25T14:00:04.948+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=445) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T14:00:04.948+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T13:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpr0owy4sh']
[2024-11-25T14:00:04.949+0000] {standard_task_runner.py:63} INFO - Started process 447 to run task
[2024-11-25T14:00:04.950+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask load
[2024-11-25T14:00:04.965+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T14:00:04.993+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [running]> on host 4f4780ae54ec
[2024-11-25T14:00:05.060+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T13:00:00+00:00'
[2024-11-25T14:00:05.061+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T14:00:05.204+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-25T14:00:05.204+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T14:00:05.205+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T14:00:05.212+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T13:00:00+00:00, execution_date=20241125T130000, start_date=20241125T140004, end_date=20241125T140005
[2024-11-25T14:00:05.244+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T14:00:05.257+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T14:00:05.262+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:19:24.620+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:19:24.646+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [queued]>
[2024-11-25T16:19:24.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [queued]>
[2024-11-25T16:19:24.656+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:19:24.678+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 13:00:00+00:00
[2024-11-25T16:19:24.689+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=341) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:19:24.691+0000] {standard_task_runner.py:63} INFO - Started process 352 to run task
[2024-11-25T16:19:24.694+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T13:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpy00kzgep']
[2024-11-25T16:19:24.697+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask load
[2024-11-25T16:19:24.730+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:19:24.764+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [running]> on host 9c7ea2cc0f0f
[2024-11-25T16:19:24.857+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T13:00:00+00:00'
[2024-11-25T16:19:24.858+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:19:25.133+0000] {logging_mixin.py:188} INFO - An error occurred: tuple index out of range
[2024-11-25T16:19:25.133+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:19:25.134+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:19:25.146+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T13:00:00+00:00, execution_date=20241125T130000, start_date=20241125T161924, end_date=20241125T161925
[2024-11-25T16:19:25.227+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:19:25.245+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:19:25.249+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-25T16:30:13.965+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T16:30:14.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [queued]>
[2024-11-25T16:30:14.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [queued]>
[2024-11-25T16:30:14.039+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T16:30:14.051+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-11-25 13:00:00+00:00
[2024-11-25T16:30:14.061+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T16:30:14.062+0000] {standard_task_runner.py:63} INFO - Started process 326 to run task
[2024-11-25T16:30:14.061+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-forecast-dag', 'load', 'scheduled__2024-11-25T13:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline.py', '--cfg-path', '/tmp/tmpxtmsty8d']
[2024-11-25T16:30:14.063+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask load
[2024-11-25T16:30:14.083+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T16:30:14.112+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-forecast-dag.load scheduled__2024-11-25T13:00:00+00:00 [running]> on host eebbb4b46189
[2024-11-25T16:30:14.191+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Urbain ZE' AIRFLOW_CTX_DAG_ID='weather-forecast-dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T13:00:00+00:00'
[2024-11-25T16:30:14.193+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T16:30:14.458+0000] {logging_mixin.py:188} INFO - Data loaded successfully to PostgreSQL!
[2024-11-25T16:30:14.459+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T16:30:14.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T16:30:14.467+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-forecast-dag, task_id=load, run_id=scheduled__2024-11-25T13:00:00+00:00, execution_date=20241125T130000, start_date=20241125T163014, end_date=20241125T163014
[2024-11-25T16:30:14.517+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T16:30:14.532+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:30:14.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
